name: Linux-64

on: push

jobs:

  build-and-release:
    runs-on: ubuntu-24.04-arm64

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.4'

      - name: Find and Replace OpenAIP
        uses: richardrigutins/replace-in-files@v2
        with:
          files: '**/*.dart'
          search-text: '@@___openaip_client_id__@@'
          replacement-text: ${{ secrets.OPENAIP_CLIENT_ID }}
          encoding: 'utf8'
          max-parallelism: 10

      - name: Update source repo
        run: sudo apt-get update
      - name: Pre-empt libunwind issue for gstreamer
        run: sudo apt-get install -y libunwind-dev
      - name: Install audioplayers dependencies
        run: sudo apt-get install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
      - name: Install dependencies
        run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

      - name: Integration Test
        run: xvfb-run flutter test integration_test/app_test.dart -d linux

      - name: Build artifacts
        run: |
          flutter build linux --release
