name: Snap-Linux

on: push

jobs:

  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.22.2'

      - name: Update source repo
        run: sudo apt-get update
      - name: Pre-empt libunwind issue for gstreamer
        run: sudo apt-get install -y libunwind-dev
      - name: Install audioplayers dependencies
        run: sudo apt-get install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
      - name: Install dependencies
        run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v2

      - name: Build Snap Image
        run: sudo snapcraft --destructive-mode
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Snap
          path: avarex*.snap
